-- استعادة أسماء المشاريع الافتراضية (كما في init-db.sql و database_service.dart).
INSERT INTO projects (name) VALUES
  ('UTC_Z5_CRC_F'),
  ('Mivida 31_CRC_F'),
  ('UTC_Z5_EMAAR Building C_F'),
  ('Zed east_ORASCOM_F'),
  ('Belle Vie_El-Hazek_F'),
  ('CAIRO GATE elain (02)_CRC_F'),
  ('Cairo gate_ACC_W'),
  ('Z1_EMAAR_F'),
  ('Community Center_CRC_W'),
  ('Terrace Zayed_CRC_W'),
  ('Silver Sands_REDCON_D'),
  ('CAR SHADE_W&M_W'),
  ('OLD CITY_ORASCOM_W'),
  ('Cairo gate-Eden_ATRUM_F'),
  ('AUC Campus Expansion_Orascom_W&F'),
  ('UTC - 2 Villa- Link International_W'),
  ('UTC - 2 Villa- Link International_F'),
  ('City Gate_CCC_W'),
  ('cairo gate - locanda_INOVOO_F'),
  ('Village West _ club_FIT-OUT_W'),
  ('Village West _Villa_W'),
  ('Mivida gardens_Atrium_F'),
  ('Village West_CRC_ F'),
  ('Up Town Cairo _Z5 _EMAAR_W'),
  ('Belle Vie _ EMAAR_W'),
  ('Village West _ CRC_ W'),
  ('Wood&More(head office)');
